### ISSUE TITLE
`Date.UTC` function is interpreted as a constructor

### ISSUE THREAD

**Issue by apsillers** [douglascrockford/JSLint#178]
JSLint incorrectly understands the built-in JavaScript function [`Date.UTC`](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.4.3) as a constructor because `UTC` begins with a capital letter. Obviously, in order to comply with JSLint's standards, developers shouldn't have non-constructors that begin with a capital letter, but apparently nobody mentioned that to the ECMAScript committee in 2011.

Could JSLint allow the unusually-capitalized standards-specified `UTC` function without complaint, when called (correctly) without `new`?

**Comment by douglascrockford** [comment]
Thanks. Please try it now.

**Comment by codinggenie** [comment]
@douglascrockford I have taken the latest commit of jslint. 
1 parent 2e33282 commit 2aca732ace5b383d09db005f045f51273f3061c2. new ...() 

The issue is popping up again. I am getting the messages "Expected 'new' before 'Date'.". I can see the fix for "Date.UTC" still in latest committed code. Is this expected ?
